# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fronted.Car'),
        ),
    ]
