# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0005_auto_20161214_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
