# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0006_booking_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
                ('Frontac', models.BooleanField()),
                ('backac', models.BooleanField()),
                ('color', models.CharField(max_length=10)),
                ('milege', models.IntegerField()),
                ('model', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(upload_to='car_images'),
        ),
        migrations.AddField(
            model_name='details',
            name='Car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fronted.Car'),
        ),
    ]
