# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0007_auto_20170511_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='Car',
        ),
    ]
