# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0008_remove_details_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fronted.Car'),
            preserve_default=False,
        ),
    ]
