# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0009_details_car'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Detail',
        ),
    ]
