# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0011_auto_20170520_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
