# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0012_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
