# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0014_auto_20170521_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fronted.Product'),
        ),
    ]
