# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0017_auto_20170523_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ManyToManyField(null=True, to='fronted.Product'),
        ),
    ]
