# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronted', '0019_auto_20170524_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ManyToManyField(null=True, to='fronted.Product'),
        ),
    ]
